---
application:
  name: "web-client"
  project: "my foodadvisor"
  organization: "QoveryCommunity"
routers:
- name: "main"
  routes:
  - application_name: "web-client"
    paths:
    - "/"
  - application_name: "strapi-api"
    paths:
    - "/api"

